### ISSUE TITLE
Driver Chip Type?

### ISSUE THREAD

**Issue by rachael7** [Skorpi08/Nextion4Marlin#1]
Hi! Thank you for your work on this! I notice you don't set the driver type in Configuration.h. Is this because you use the standard 4988 drivers in your machine? I have TMC2208 drivers - do you know if I should specify "TMC2208" or "TMC2208_STANDALONE"? Thanks!

**Comment by Skorpi08** [comment]
Yes, i have standard 4988.
You need TMC2208_STANDALONE if you use it without UART.

**Comment by rachael7** [comment]
I'm using it however Hictop/Tenlog configured it, so I'll assume that's without UART. Thank you so much! Is this build working for you?

**Comment by Skorpi08** [comment]
sure

**Comment by rachael7** [comment]
Wonderful! Thanks again!

**Comment by rachael7** [comment]
One last question, if I can impose upon you again. So basically, the procedure here is to build and flash your Marlin 2.0.6 build and flash the Hictop D3 Hero.tft file to the display? Is that all there is to it?

**Comment by Skorpi08** [comment]
yes
