### ISSUE TITLE
Intelligent display

### ISSUE THREAD

**Issue by Voodoobrew101** [Skorpi08/Nextion4Marlin#13]
Pardon my noob but,
My Tenlog has this display, it looks different then the one on their website. 
https://www.aliexpress.com/item/4000351236094.html?spm=2114.12057483.0.0.2ced2ae872eV61

But nothing seems like it has a bootloader that will update from my sdcards. I load the Hictop D3 Hero.tft to the SD place it in the LCD SD slot and Power the unit on but it doesn't load, any advise?
anytime I update Firmware on the mother board, I have been doing it with ArduinoISP Direct.
Any Idea if there a downloadable bootloader anywhere?

**Comment by Skorpi08** [comment]
This is the newer generation, it doesn't work with it.
