### ISSUE TITLE
Inverted extruders

### ISSUE THREAD

**Issue by NeuralDip** [Skorpi08/Nextion4Marlin#2]
Hello, this is a great delivery.
i have though a couple of issues, one being that the tools T0 and T1 are inverted while temp setting and filament change.
by inverted i mean that i have to change the temperature of T1 in order to print with T0 and i also have to load T1 in order to Load filament in T0.
i am about to hack the marlin code in order to fix this, but i hope this has an easier solution in the Nextion firmware.
Best regards

**Comment by Skorpi08** [comment]
There are 2 possibilities.

1. Swap the plugs on the back that lead to the Hotend.
2. Change in Marlin pins_TENLOG_D3_HERO.h

#define E0_STEP_PIN        57//26
#define E0_DIR_PIN         58//28
#define E0_ENABLE_PIN      59//24

#define E1_STEP_PIN        26//57
#define E1_DIR_PIN         28//58
#define E1_ENABLE_PIN      24//59

//
// Temperature Sensors
//
#define TEMP_0_PIN          15//13   // Analog Input
#define TEMP_1_PIN          13//15   // Analog Input
#define TEMP_BED_PIN        14   // Analog Input

//
// Heaters
//
#define HEATER_0_PIN        11//10
#define HEATER_1_PIN        10//11
#define HEATER_BED_PIN      8

**Comment by NeuralDip** [comment]
Hey that worked!
i changed the Pins,
Thanks a lot.
I would be nice though if you shared the LCD source too, so we could add
our own functionality..
best regards,

**Comment by klack** [comment]
Confirmed that I also had to swap these pins and now they are no longer reversed.

@NeuralDip Good to see you, thanks for your previous work on the tenlog configs too!

**Comment by ccomincini** [comment]
I use a Tenlog D3 with Hictop titan. It seems to me that also extruder fans are swapped. The fan for the hot-end cooling is swapped with rhe one for the printed piece cooling
